site_name: Larq
site_description: "Larq is an open-source deep learning library based on TensorFlow and Keras for training neural networks with extremely low-precision weights and activations, such as Binarized Neural Networks."
site_author: "Plumerai"
site_url: "https://docs.larq.dev/"

nav:
  - Larq:
      - Getting Started: index.md
      - User Guides:
          - Key Concepts: larq/guides/key-concepts.md
          - Building BNNs: larq/guides/bnn-architecture.md
          - Training BNNs: larq/guides/bnn-optimization.md
      - Tutorials:
          - Introduction to BNNs with Larq: larq/tutorials/mnist.ipynb
          - BinaryNet on CIFAR10: larq/tutorials/binarynet_cifar10.ipynb
      - API:
          - Layers: larq/api/layers.md
          - Quantizers: larq/api/quantizers.md
          - Activations: larq/api/activations.md
          - Constraints: larq/api/constraints.md
          - Context: larq/api/context.md
          - Callbacks: larq/api/callbacks.md
          - Optimizers: larq/api/optimizers.md
          - Math: larq/api/math.md
          - Models: larq/api/models.md
          - Metrics: larq/api/metrics.md
      - FAQ: faq.md
  - Zoo:
      - Getting Started: zoo/index.md
      - Tutorials: zoo/tutorials.ipynb
      - API:
          - zoo: zoo/api/index.md
          - zoo.literature: zoo/api/literature.md
          - zoo.sota: zoo/api/sota.md
  - Compute Engine:
      - Getting Started: compute-engine/index.md
      - Converter: compute-engine/converter.md
      - Inference: compute-engine/inference.md
      - Quickstart Android: compute-engine/quickstart_android.md
      - Build:
          - Build from source: compute-engine/build.md
          - Build for ARM: compute-engine/build_arm.md
      - API: compute-engine/api/index.md

repo_url: https://github.com/larq/larq
repo_name: larq/larq
edit_uri: ""
theme:
  name: material
  custom_dir: theme
  logo: images/logo-big-font.svg
  favicon: images/favicon-32.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: white
    # accent: blue
  font:
    text: "Work Sans"
    code: "Roboto Mono"
  features:
    - tabs
    - instant

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/larq
    - icon: fontawesome/solid/comment
      link: https://spectrum.chat/larq
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PlumeraiHQ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/plumerai/

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: plot-activation
          class: larq-activation
          format: !!python/name:plot_altair.plot_activation
        - name: plot-altair
          class: larq-altair
          format: !!python/name:plot_altair.html_format
        - name: netron
          class: larq-netron
          format: !!python/name:netron_link.html_format
        - name: summary
          class: larq-netron
          format: !!python/name:model_summary.html_format
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - toc:
      permalink: true

extra_javascript:
  - extra.js
extra_css:
  - styles.css

google_analytics:
  - "UA-144491780-1"
  - "auto"

plugins:
  - search
  - minify:
      minify_html: true
  - mknotebooks:
      execute: false
      enable_default_jupyter_cell_styling: false
      enable_default_pandas_dataframe_styling: false
